### ISSUE TITLE
I want complete follow function,but it can't work in koa,so how should I do?

### ISSUE THREAD

**Issue by dsgygb** [dionoid/koa-request#2]
I want complete follow function,but it can't work in koa,so how should I do?

    var request= require('koa-request');
    var check=function * (o){
    var options ={
        url: o.url
    }
    var response=yield request(options);
    return response;
    };
    var o={url : "http://example.com/api/"};
    var checkResponse = check(o);
    var res = checkResponse.next();
    var ret = checkResponse.next(res);

**Comment by dionoid** [comment]
Hi dsgygb, you can use the `co` framework for this (see code example below).
Or maybe you like a wrapper-library like request-promise better.

--DionoiD

```
var co = require('co');
var request= require('koa-request');

var getResponse = co.wrap(function *(options) {
    return yield request(options); //Yay, HTTP requests with no callbacks!
});

var options = {
    url: 'https://api.github.com/repos/dionoid/koa-request',
    headers: { 'User-Agent': 'request' }
};

getResponse(options).then(function (response) {
    var info = JSON.parse(response.body);
    console.log('my full name is ' + info.full_name);
});
```
